machine:
  environment:
    ANDROID_HOME: /usr/local/android-sdk-linux
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
  java:
    version: oraclejdk8

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN

general:
   artifacts:
     - $CIRCLE_TEST_REPORTS

dependencies:
  pre:
    # Android SDK Platform 25
    - if [ ! -d "/usr/local/android-sdk-linux/platforms/android-25" ]; then echo y | android update sdk --no-ui --all --filter "android-25"; fi
    # Android SDK Build-tools, revision 25.0.2
    - if [ ! -d "/usr/local/android-sdk-linux/build-tools/25.0.2" ]; then echo y | android update sdk --no-ui --all --filter "build-tools-25.0.2"; fi
    # Android Support Repository, revision 44 / Local Maven repository for Support Libraries
    - if [ ! -d "/usr/local/android-sdk-linux/extras/android/m2repository/com/android/support/design/25.2.0" ]; then echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"; fi
    # Constraint Layout 1.0.1
    - if [ ! -d  "usr/local/android-sdk-linux/extras/m2repository/com/android/support/constraint/constraint-layout/1.0.1]; then echo y | android update sdk --no-ui --all -filter "extra-android-m2repository-constraint-layout"

    # Google Support Repository, revision 44 / Local Maven repository for Google Play Services
    - if [ ! -d "/usr/local/android-sdk-linux/extras/google/m2repository/com/google/android/gms/play-services/10.2.0" ]; then echo y | android update sdk --no-ui --all --filter "extra-google-m2repository"; fi
    - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies

  cache_directories:
    - '~/.android'
    - '~/android'
    - '/usr/local/android-sdk-linux/platforms/android-25'
    - '/usr/local/android-sdk-linux/build-tools/25.0.2'
    - '/usr/local/android-sdk-linux/extras/android/m2repository'

test:
  override:
    - ./gradlew assembleDebug testDebugUnitTest --no-daemon -Dpre-dex=false -Porg.gradle.parallel=false -Pcom.android.build.threadPoolSize=1 --stacktrace
  post:
    # Move unit test XML to correct directory
    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;